{\rtf1\ansi\ansicpg1252\cocoartf2709
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fswiss\fcharset0 Helvetica;}
{\colortbl;\red255\green255\blue255;}
{\*\expandedcolortbl;;}
\paperw11900\paperh16840\margl1440\margr1440\vieww11520\viewh8400\viewkind0
\pard\tx720\tx1440\tx2160\tx2880\tx3600\tx4320\tx5040\tx5760\tx6480\tx7200\tx7920\tx8640\pardirnatural\partightenfactor0

\f0\fs24 \cf0 name: Build and Deploy Jekyll Site\
\
on:\
  push:\
    branches:\
      - main  # Your default branch\
\
jobs:\
  build:\
    runs-on: ubuntu-latest\
\
    steps:\
    - uses: actions/checkout@v2\
\
    # Set up Ruby for Jekyll\
    - name: Set up Ruby\
      uses: ruby/setup-ruby@v1\
      with:\
        ruby-version: '3.0'\
        bundler-cache: true\
\
    # Set up Python (if needed)\
    - name: Set up Python\
      uses: actions/setup-python@v2\
      with:\
        python-version: '3.x'\
\
    # Install Dependencies\
    - name: Install Dependencies\
      run: |\
        python3 -m venv venv\
        source venv/bin/activate\
        pip install -r requirements.txt\
        bundle install\
\
    # Build the Jekyll site\
    - name: Build Jekyll Site\
      run: bundle exec jekyll build\
}